### ISSUE TITLE
Can it check github windows binaries?

### ISSUE THREAD

**Issue by wyonghao** [manur/MATLAB-git#8]
I installed github on windows. it has git binary on its own "portable" path but not in the system path. It would be nice to have git.m work with git come with github installations.
thanks

**Comment by manur** [comment]
Hello @wyonghao,

Sorry for the very late response.

At this time, there are no plans to make an exception for the github installation, though it'd be a convenient default option. You're welcome to do something along the lines of what the parent suggests.
